image: registry.remoi.fr/robotframework/browser-image

stages:
  - test

test-image:
  stage: test
  rules:
    - if: ('$CI_COMMIT_TAG' && $CI_PIPELINE_SOURCE == "merge_request_event")
    - changes:
        - .gitlab-ci.yml
        - requirements.txt
        - test/test.robot
  script: 
    - python3 --version
    - python3 -m pip install -r requirements.txt   
    - robot test/


